-- Dedup do glossário: truncar tudo, adicionar constraints UNIQUE, reinserir dados.
-- O seed rodou 3x sem constraints → 120 linhas. Solução: limpar e reinserir.

TRUNCATE TABLE glossario;

ALTER TABLE glossario
  DROP CONSTRAINT IF EXISTS glossario_slug_unique,
  DROP CONSTRAINT IF EXISTS glossario_termo_unique;

ALTER TABLE glossario
  ADD CONSTRAINT glossario_slug_unique  UNIQUE (slug),
  ADD CONSTRAINT glossario_termo_unique UNIQUE (termo);

-- Reinserção dos 50 termos com ON CONFLICT (slug) para idempotência futura
INSERT INTO glossario (slug, termo, definicao_simples, definicao_tecnica, categoria, exemplo, termos_relacionados) VALUES

('projeto-de-lei', 'Projeto de Lei (PL)', 'É uma proposta para criar ou mudar uma lei. Qualquer deputado, senador ou o próprio presidente pode apresentar um PL, que precisa ser aprovado pelo Congresso para virar lei.', 'Instrumento legislativo previsto no art. 61 da Constituição Federal de 1988 que propõe a criação, modificação ou revogação de normas infraconstitucionais. Pode ser de iniciativa parlamentar, do Poder Executivo, do STF, dos Tribunais Superiores, do Ministério Público ou popular (art. 61 §2º CF/88).', 'legislativo', 'O PL 1234/2025 propõe aumentar a pena para crimes de corrupção eleitoral.', ARRAY['proposta-de-emenda-a-constituicao','projeto-de-lei-complementar','regime-de-urgencia','plenario']),

('proposta-de-emenda-a-constituicao', 'Proposta de Emenda à Constituição (PEC)', 'É um projeto para alterar a Constituição Federal, que é a lei máxima do país. Por mexer nas regras mais importantes do Brasil, sua aprovação é muito mais difícil e demorada do que a de uma lei comum.', 'Proposição legislativa de rito rígido regulada pelo art. 60 da Constituição Federal de 1988. Exige aprovação por três quintos dos membros em ambas as Casas do Congresso Nacional, em dois turnos de votação em cada uma, sendo promulgada pelas Mesas Diretoras.', 'legislativo', 'A PEC da reforma tributária foi promulgada após intensas rodadas de debate.', ARRAY['projeto-de-lei','promulgacao','turno-de-votacao','quorum']),

('projeto-de-lei-complementar', 'Projeto de Lei Complementar (PLP)', 'É um tipo de lei especial que serve para detalhar assuntos importantes que a Constituição expressamente mandou regulamentar. Para ser aprovado, exige o voto favorável de mais da metade de todos os parlamentares.', 'Espécie normativa infraconstitucional prevista no art. 69 da Constituição Federal de 1988, de âmbito reservado aos temas expressamente indicados no texto constitucional. Sua aprovação requer quórum qualificado de maioria absoluta nas duas Casas do Congresso.', 'legislativo', 'O Congresso aprovou o PLP que define novas regras para o teto de gastos do governo federal.', ARRAY['projeto-de-lei','quorum','plenario']),

('projeto-de-decreto-legislativo', 'Projeto de Decreto Legislativo (PDL)', 'É uma proposta do Congresso para tomar decisões que valem fora do parlamento, mas que não dependem do aval do presidente, como aprovar tratados com outros países ou suspender ordens do governo.', 'Proposição legislativa destinada a regular matérias de competência exclusiva do Congresso Nacional que geram efeitos externos ao parlamento, conforme o art. 49 da Constituição Federal de 1988. Dispensa sanção ou veto presidencial.', 'legislativo', 'Foi apresentado um PDL para suspender a portaria do governo sobre o comércio de combustíveis.', ARRAY['resolucao','veto']),

('medida-provisoria', 'Medida Provisória (MPV)', 'É uma regra urgente criada pelo presidente que já começa a valer como lei assim que é publicada. No entanto, ela precisa ser votada e aprovada pelo Congresso em até 120 dias para não perder a validade.', 'Ato unipessoal de caráter excepcional adotado pelo Presidente da República com força de lei, regulamentado pelo art. 62 da Constituição Federal de 1988. Exige requisitos cumulativos de relevância e urgência, vigendo por até 120 dias.', 'legislativo', 'O Executivo editou uma MPV para liberar recursos emergenciais para estados afetados por enchentes.', ARRAY['projeto-de-lei','regime-de-urgencia','plenario']),

('cota-para-exercicio-da-atividade-parlamentar', 'Cota para Exercício da Atividade Parlamentar (CEAP)', 'É uma verba mensal dada a deputados e senadores para pagar despesas do seu trabalho de representação, como passagens de avião, gasolina, aluguel de escritório e contas de telefone.', 'Verba indenizatória de caráter público instituída na Câmara dos Deputados pelo Ato da Mesa nº 43/2009. Destina-se exclusivamente ao custeio de despesas vinculadas ao exercício do mandato parlamentar, sujeita a limites mensais por estado de origem.', 'financeiro', 'O deputado utilizou a CEAP para custear as passagens aéreas de Brasília até sua base eleitoral.', ARRAY['emenda-parlamentar','portal-da-transparencia','siafi']),

('emenda-parlamentar', 'Emenda Parlamentar', 'É uma proposta apresentada por deputados ou senadores para direcionar uma parte do dinheiro do orçamento do governo para obras, hospitais ou melhorias em suas regiões.', 'Instrumento constitucional previsto no art. 166 da Constituição Federal de 1988 que permite aos parlamentares propor alterações ao projeto de Lei Orçamentária Anual (LOA), alocando recursos públicos para políticas e obras específicas.', 'financeiro', 'A prefeitura obteve uma emenda parlamentar de R$ 500 mil para pavimentar as ruas do centro.', ARRAY['emenda-impositiva','emenda-pix','emenda-de-bancada','siafi']),

('emenda-pix', 'Emenda Pix', 'É um tipo de transferência rápida que envia o dinheiro da emenda de um deputado direto para a conta de uma prefeitura ou estado, sem necessidade de contratos ou convênios demorados.', 'Modalidade de emenda individual impositiva sob a forma de transferência especial, instituída pela Emenda Constitucional nº 105/2019 e regulada pelo art. 166-A da Constituição Federal. Dispensa a intermediação de órgãos federais.', 'financeiro', 'O município recebeu uma emenda Pix para a reforma de uma escola de forma simplificada.', ARRAY['emenda-parlamentar','emenda-impositiva','siafi']),

('emenda-de-bancada', 'Emenda de Bancada', 'É uma verba do orçamento decidida em conjunto por todos os deputados e senadores de um mesmo estado para financiar uma grande obra que beneficie toda aquela região.', 'Emenda parlamentar de caráter coletivo, proposta pela bancada de deputados e senadores representantes de um mesmo estado da federação, nos termos do art. 166 da CF/88. Possui execução impositiva conforme a EC nº 100/2019.', 'financeiro', 'A emenda de bancada do Paraná garantiu os recursos necessários para a duplicação de uma rodovia.', ARRAY['emenda-parlamentar','emenda-impositiva']),

('emenda-impositiva', 'Emenda Impositiva', 'É a emenda parlamentar que o governo é obrigado por lei a pagar e executar, não podendo segurar esse dinheiro por negociação política.', 'Recurso orçamentário cuja execução financeira pelo Poder Executivo é obrigatória, conforme as regras estabelecidas pelas EC nº 86/2015 e EC nº 100/2019, com ressalva para impedimentos técnicos intransponíveis.', 'financeiro', 'A execução da emenda impositiva garantiu o repasse para o hospital de forma direta.', ARRAY['emenda-parlamentar','emenda-pix','emenda-de-bancada']),

('plenario', 'Plenário', 'É o local principal onde todos os parlamentares se reúnem para debater e votar os projetos mais importantes que virarão leis no país.', 'Órgão deliberativo máximo e soberano de uma Casa Legislativa, composto pela totalidade dos seus membros em exercício. Suas decisões dependem da observância de quórum e votação fixados na Constituição.', 'legislativo', 'A reforma tributária foi aprovada pelo Plenário do Senado em votação nominal.', ARRAY['comissao','quorum','sessao-ordinaria']),

('comissao', 'Comissão', 'É um grupo menor de parlamentares especializado em estudar temas específicos, como saúde ou educação, para dar pareceres e discutir projetos antes de irem para votação geral.', 'Órgão técnico-colegiado, permanente ou temporário, instituído com base na representação proporcional dos partidos no Legislativo (art. 58 da CF/88). Exerce funções opinativas, técnicas e de fiscalização.', 'legislativo', 'O projeto de lei passou pelas discussões técnicas da Comissão de Constituição e Justiça.', ARRAY['plenario','destaque','obstrucao']),

('quorum', 'Quórum', 'É o número mínimo de deputados ou senadores que precisam estar presentes no plenário para que uma votação possa acontecer e ter validade legal.', 'Número mínimo de parlamentares exigido pela Constituição Federal ou pelos regimentos internos para a abertura de sessões e realização de deliberações válidas nas Casas Legislativas (art. 47 da CF/88).', 'legislativo', 'O presidente da Câmara cancelou a votação porque não havia quórum suficiente no plenário.', ARRAY['plenario','votacao-nominal','sessao-ordinaria']),

('sessao-ordinaria', 'Sessão Ordinária', 'É a reunião de trabalho comum e diária dos deputados e senadores, realizada nos dias e horários normais do calendário oficial do Congresso.', 'Sessão plenária regular realizada nos dias e horários previstos nos regimentos internos das Casas Legislativas, durante os períodos normais de funcionamento do Congresso Nacional (art. 57 da CF/88).', 'legislativo', 'A apresentação dos discursos de liderança ocorreu durante a sessão ordinária desta tarde.', ARRAY['sessao-extraordinaria','plenario','quorum']),

('sessao-extraordinaria', 'Sessão Extraordinária', 'É uma reunião extra de trabalho agendada fora dos horários tradicionais ou durante o recesso para votar propostas muito urgentes que não podem esperar.', 'Sessão plenária realizada em dias ou horários distintos daqueles destinados às sessões ordinárias, convocada pelo presidente da Casa Legislativa para deliberar sobre pauta específica e urgente.', 'legislativo', 'O plenário convocou uma sessão extraordinária à noite para votar o novo arcabouço fiscal.', ARRAY['sessao-ordinaria','plenario','regime-de-urgencia']),

('votacao-nominal', 'Votação Nominal', 'É o tipo de votação em que o voto individual de cada parlamentar é registrado no painel eletrônico, permitindo que qualquer cidadão saiba exatamente como seu representante votou.', 'Processo de votação parlamentar em que se registra formalmente a manifestação individual de cada parlamentar (sim, não ou abstenção) no painel eletrônico, garantindo publicidade ativa e transparência.', 'legislativo', 'Os cidadãos acompanharam pela internet a votação nominal da cassação de mandato.', ARRAY['votacao-simbolica','plenario','quorum']),

('votacao-simbolica', 'Votação Simbólica', 'É um jeito rápido de votar em projetos que já têm consenso, no qual os parlamentares a favor continuam sentados e os contra se levantam, sem registrar o voto de cada um no painel.', 'Processo de deliberação coletiva no qual não há registro individual de nomes e votos. O presidente proclama o resultado com base na postura física assumida pelos parlamentares em plenário.', 'legislativo', 'A concessão do título de utilidade pública foi aprovada em votação simbólica.', ARRAY['votacao-nominal','plenario']),

('obstrucao', 'Obstrução', 'É uma tática usada por partidos políticos para atrasar ou impedir que um projeto seja votado, seja fazendo discursos longos ou deixando de marcar presença em plenário.', 'Conjunto de manobras regimentais lícitas utilizadas por minorias ou oposição para adiar ou impedir a deliberação de matérias, recorrendo a requerimentos de adiamento ou retirada de quórum.', 'legislativo', 'A oposição entrou em obstrução para adiar a votação de um novo imposto.', ARRAY['plenario','quorum','destaque']),

('destaque', 'Destaque', 'É um pedido feito por um parlamentar para separar uma parte de um projeto de lei e votá-la isoladamente, tentando mudar ou retirar aquele trecho específico do texto.', 'Instrumento processual previsto nos regimentos internos das Casas Legislativas que permite a exclusão temporária de um trecho de uma proposição para votação separada em plenário.', 'legislativo', 'O partido apresentou um destaque para retirar o trecho que cortava benefícios de saúde.', ARRAY['projeto-de-lei','obstrucao','plenario']),

('regime-de-urgencia', 'Regime de Urgência', 'É um procedimento acelerado que dispensa vários prazos e discussões normais para que um projeto de lei urgente seja votado rapidamente.', 'Procedimento excepcional que suprime prazos e formalidades regimentais ordinárias (como análise prévia de comissões temáticas), permitindo que um projeto seja pautado diretamente no Plenário.', 'legislativo', 'O projeto que estabelece o plano nacional de defesa civil tramitou em regime de urgência.', ARRAY['projeto-de-lei','sessao-extraordinaria','plenario']),

('turno-de-votacao', 'Turno de Votação', 'É cada uma das rodadas obrigatórias de debate e votação pelas quais um projeto precisa passar na Câmara ou no Senado antes de ser aprovado.', 'Fase de discussão e deliberação de uma matéria no plenário. Leis ordinárias passam por turno único, enquanto Propostas de Emenda à Constituição exigem dois turnos de votação em cada Casa.', 'legislativo', 'A PEC que altera regras previdenciárias foi aprovada no primeiro turno de votação.', ARRAY['proposta-de-emenda-a-constituicao','plenario','quorum']),

('promulgacao', 'Promulgação', 'É o ato oficial que declara que uma nova lei existe de verdade e que ela deve começar a ser cumprida por todos os cidadãos.', 'Ato solene declaratório da existência da lei, que atesta sua validade constitucional e ordena sua fiel execução. É realizado pelo chefe do Executivo ou pelas Mesas do Congresso Nacional.', 'institucional', 'As Mesas do Congresso realizaram a sessão solene de promulgação da emenda à Constituição.', ARRAY['sancao','veto','projeto-de-lei']),

('sancao', 'Sanção', 'É o "sim" do presidente da República a um projeto aprovado pelo Congresso, transformando-o oficialmente em lei nacional.', 'Ato político e jurídico de concordância do Presidente da República com o projeto de lei aprovado pelo Congresso, previsto no art. 66 da CF/88. Pode ser expressa ou tácita.', 'institucional', 'O projeto que prevê novos direitos para o consumidor recebeu sanção presidencial.', ARRAY['veto','promulgacao','projeto-de-lei']),

('veto', 'Veto', 'É o "não" do presidente a um projeto de lei aprovado pelo Congresso, recusando-o por considerá-lo inconstitucional ou ruim para os interesses do país.', 'Ato formal e fundamentado do Poder Executivo que rejeita a conversão de um projeto de lei em norma jurídica (art. 66 da CF/88). Pode ser total ou parcial, cabendo derrubada pelo Congresso.', 'institucional', 'O Congresso realizou uma sessão conjunta e derrubou o veto do presidente à desoneração fiscal.', ARRAY['sancao','resolucao','plenario']),

('resolucao', 'Resolução', 'É uma regra interna criada por uma das Casas do Congresso para organizar seus próprios serviços administrativos e rotinas de funcionamento.', 'Espécie normativa de competência privativa da Câmara dos Deputados, do Senado Federal ou do Congresso, destinada a disciplinar matérias político-administrativas e regulamentares de interesse interno.', 'institucional', 'A resolução aprovada no Senado criou um novo comitê técnico focado em inteligência artificial.', ARRAY['plenario','veto']),

('legislatura', 'Legislatura', 'É o período de quatro anos durante o qual os parlamentares eleitos exercem suas funções no Congresso até que ocorra uma nova eleição.', 'Período temporal de funcionamento e representação do Poder Legislativo federal, com duração fixada em quatro anos, nos termos do art. 44 da Constituição Federal de 1988.', 'eleitoral', 'A atual legislatura da Câmara conta com maior fragmentação partidária.', ARRAY['mandato','suplente']),

('mandato', 'Mandato', 'É a autorização que os cidadãos dão pelo voto para que um político represente o povo e crie leis durante um tempo predeterminado.', 'Delegação temporária de soberania popular outorgada pelo corpo eleitoral por meio de sufrágio, que confere legitimidade jurídica para o exercício de cargo político eletivo no Executivo ou Legislativo.', 'eleitoral', 'Os senadores exercem um mandato de oito anos, renovados parcialmente a cada eleição.', ARRAY['legislatura','suplente','candidatura']),

('suplente', 'Suplente', 'É o candidato reserva de uma lista partidária que assume o cargo de deputado ou vereador se o titular pedir licença ou for afastado.', 'Candidato registrado por partido ou federação que, na ordem decrescente de votos, não alcança vaga imediata no parlamento, figurando como reserva legal para substituição de titulares.', 'eleitoral', 'O suplente assumiu o mandato após o deputado titular assumir uma secretaria de Estado.', ARRAY['mandato','eleicao-proporcional','legislatura']),

('coligacao', 'Coligação', 'É uma união temporária de partidos políticos que decidem apoiar juntos um mesmo candidato para cargos como prefeito, governador ou presidente.', 'Aliança eleitoral temporária formada por partidos políticos para disputar cargos executivos ou majoritários (art. 17, §1º da CF/88). É proibida nas eleições proporcionais por força da EC nº 97/2017.', 'eleitoral', 'Cinco partidos de centro formaram a coligação que disputará a prefeitura da capital.', ARRAY['federacao-partidaria','eleicao-majoritaria']),

('federacao-partidaria', 'Federação Partidária', 'É uma união de dois ou mais partidos que devem agir de forma unificada e como se fossem uma única sigla nas eleições e no governo por pelo menos quatro anos.', 'Consórcio de partidos políticos com atuação unificada em caráter permanente por no mínimo quatro anos, sob estatuto e programa nacionais comuns, conforme a Lei nº 14.208/2021.', 'eleitoral', 'A federação partidária uniu três siglas médias para aumentar sua força de votação no Congresso.', ARRAY['coligacao','janela-partidaria','clausula-de-barreira']),

('janela-partidaria', 'Janela Partidária', 'É um período de trinta dias antes da eleição no qual deputados e vereadores podem mudar de partido político sem perder o cargo que possuem.', 'Prazo de 30 dias que ocorre seis meses antes das eleições, regulado pelo art. 22-A da Lei nº 9.096/1995. Permite aos ocupantes de cargos proporcionais a migração com justa causa legal.', 'eleitoral', 'O vereador aproveitou a janela partidária para ingressar na sigla pela qual disputará a eleição.', ARRAY['federacao-partidaria','mandato','candidatura']),

('candidatura', 'Candidatura', 'É o processo legal pelo qual uma pessoa, aprovada em convenção por seu partido, registra-se oficialmente na Justiça Eleitoral para disputar um cargo político.', 'Ato jurídico-eleitoral pelo qual um cidadão em pleno gozo dos direitos políticos postula concorrer a um cargo público eletivo, cumprindo condições de elegibilidade sob as regras da Lei nº 9.504/1997.', 'eleitoral', 'A Justiça Eleitoral deferiu a candidatura após comprovação de regularidade documental.', ARRAY['inelegibilidade','ficha-limpa','impugnacao-de-mandato']),

('eleicao-proporcional', 'Eleição Proporcional', 'É o sistema que elege deputados e vereadores distribuindo as vagas para os partidos conforme o total de votos que cada legenda ou federação recebeu, e não apenas pelo voto individual.', 'Sistema de representação proporcional regulado pelos arts. 105 a 113 do Código Eleitoral. As cadeiras do Legislativo são distribuídas às siglas que atingem o quociente eleitoral.', 'eleitoral', 'A eleição proporcional viabilizou a representação de minorias no legislativo estadual.', ARRAY['eleicao-majoritaria','suplente','clausula-de-barreira']),

('eleicao-majoritaria', 'Eleição Majoritária', 'É o sistema que elege prefeitos, governadores, senadores e o presidente, onde o candidato que receber mais votos válidos ganha a disputa eleitoral.', 'Sistema eleitoral no qual é consagrado vencedor o candidato que obtiver a maioria absoluta (como em grandes municípios, estados e União) ou maioria simples (caso de senadores), segundo o art. 77 da CF/88.', 'eleitoral', 'O governador foi eleito por maioria de votos no primeiro turno da eleição majoritária.', ARRAY['eleicao-proporcional','coligacao','mandato']),

('clausula-de-barreira', 'Cláusula de Barreira', 'É uma regra que exige que os partidos alcancem uma votação mínima no país inteiro para terem direito a dinheiro público e tempo de propaganda gratuita na televisão.', 'Regra constitucional de desempenho partidário introduzida pela EC nº 97/2017 (art. 17, §3º da CF/88). Restringe recursos públicos e tempo de propaganda aos partidos que alcançarem votação mínima.', 'eleitoral', 'O partido focou suas campanhas nos grandes centros para superar a cláusula de barreira.', ARRAY['federacao-partidaria','fundo-partidario']),

('fundo-eleitoral', 'Fundo Eleitoral (FEFC)', 'É um montante de dinheiro público do orçamento federal distribuído aos partidos para pagar exclusivamente as campanhas eleitorais dos candidatos a cada dois anos.', 'Fundo Especial de Financiamento de Campanha (FEFC), instituído pelas Leis nº 13.487/2017 e nº 13.488/2017. Trata-se de recurso público destinado ao custeio exclusivo das campanhas eleitorais.', 'financeiro', 'A distribuição das verbas do Fundo Eleitoral seguiu critérios de representatividade das bancadas.', ARRAY['fundo-partidario','financiamento-de-campanha','prestacao-de-contas']),

('fundo-partidario', 'Fundo Partidário', 'É uma verba pública anual enviada aos partidos políticos para custear despesas rotineiras, como aluguel de sedes, salários de funcionários e pesquisas de opinião.', 'Fundo Especial de Assistência Financeira aos Partidos Políticos, regulado pela Lei nº 9.096/1995. Destina-se à manutenção ordinária e permanente da infraestrutura dos diretórios políticos.', 'financeiro', 'O partido destinou parte do Fundo Partidário para a formação política de novos quadros.', ARRAY['fundo-eleitoral','clausula-de-barreira']),

('financiamento-de-campanha', 'Financiamento de Campanha', 'É o conjunto de regras sobre como os candidatos conseguem arrecadar dinheiro para suas propagandas e viagens de eleição, vindos principalmente do governo ou de doações de pessoas físicas.', 'Arcabouço normativo estabelecido pela Lei nº 9.504/1997 que disciplina as fontes e limites de captação de recursos para campanhas, proibindo repasses e doações corporativas.', 'financeiro', 'O candidato detalhou as doações de pessoas físicas que financiaram sua campanha.', ARRAY['fundo-eleitoral','prestacao-de-contas','portal-da-transparencia']),

('prestacao-de-contas', 'Prestação de Contas', 'É o relatório detalhado que candidatos e partidos políticos devem entregar à Justiça mostrando cada centavo que receberam e gastaram em suas atividades e campanhas.', 'Procedimento jurisdicional obrigatório perante a Justiça Eleitoral (Lei nº 9.504/1997) destinado ao controle e fiscalização de contas eleitorais. A desaprovação pode obstar a diplomação.', 'financeiro', 'A equipe jurídica do candidato finalizou a prestação de contas no prazo fixado pela Justiça.', ARRAY['financiamento-de-campanha','fundo-eleitoral','ficha-limpa']),

('ficha-limpa', 'Ficha Limpa', 'É a lei que proíbe políticos condenados por crimes graves em órgãos colegiados, ou que perderam o mandato por mau comportamento, de concorrerem a novas eleições.', 'Lei Complementar nº 135/2010, que alterou a Lei das Inelegibilidades (LC nº 64/1990). Impõe inelegibilidade por oito anos a cidadãos condenados por órgãos colegiados judiciais por crimes graves.', 'eleitoral', 'A candidatura do prefeito foi barrada com base na Lei da Ficha Limpa devido a uma decisão colegiada.', ARRAY['inelegibilidade','candidatura','cassacao']),

('inelegibilidade', 'Inelegibilidade', 'É o impedimento legal temporário que proíbe um cidadão de disputar uma eleição para qualquer cargo público.', 'Ausência temporária de capacidade eleitoral passiva, caracterizada pelo impedimento legal ou constitucional de concorrer a cargos públicos, conforme o art. 14, §9º da CF/88.', 'eleitoral', 'A Justiça Eleitoral decretou a inelegibilidade do ex-governador por abuso de poder econômico.', ARRAY['ficha-limpa','candidatura','impugnacao-de-mandato']),

('impugnacao-de-mandato', 'Impugnação de Mandato', 'É um processo judicial na Justiça Eleitoral para anular o mandato de um político eleito, caso seja provado que ele fraudou, comprou votos ou usou abuso de poder para vencer.', 'Ação de Impugnação de Mandato Eletivo (AIME), prevista no art. 14, §§ 10 e 11 da CF/88. Proposta em até 15 dias após a diplomação sob acusação de corrupção ou abuso de poder.', 'eleitoral', 'O diretório partidário ajuizou ação de impugnação de mandato contra o candidato reeleito.', ARRAY['inelegibilidade','cassacao','candidatura']),

('cassacao', 'Cassação', 'É a perda punitiva do mandato de um político, decidida pelo Congresso ou pela Justiça Eleitoral, por ter cometido crimes, fraudes ou agido de forma antiética.', 'Extinção forçada de mandato eletivo por meio de decisão sancionatória do Poder Legislativo (quebra de decoro - art. 55 da CF/88) ou do Poder Judiciário Eleitoral (fraudes eleitorais).', 'institucional', 'A cassação do vereador foi decidida por ampla maioria após comissão de inquérito ética.', ARRAY['impeachment','crime-de-responsabilidade','ficha-limpa']),

('recall', 'Recall', 'É a possibilidade de os eleitores fazerem uma votação especial para retirar do cargo um político eleito antes do fim de seu mandato, caso estejam insatisfeitos.', 'Mecanismo de democracia direta para revogação do mandato popular de um eleito antes de seu término regulamentar, por meio de petição e voto direto dos cidadãos. Inexistente no ordenamento constitucional brasileiro atual.', 'eleitoral', 'Juristas debatem a viabilidade de PEC para implementar o mecanismo de recall no nível municipal.', ARRAY['mandato','cassacao','impeachment']),

('impeachment', 'Impeachment', 'É o processo político no qual o Congresso julga e pode afastar definitivamente do poder um presidente, governador ou prefeito por cometer crimes contra a administração pública.', 'Procedimento político-jurídico regulado pela Lei Federal nº 1.079/1950 e pelos arts. 85 e 86 da Constituição Federal. Processado na Câmara dos Deputados e julgado perante o Senado Federal.', 'institucional', 'O Senado Federal instaurou a fase final do julgamento do processo de impeachment.', ARRAY['crime-de-responsabilidade','cassacao','tcu']),

('crime-de-responsabilidade', 'Crime de Responsabilidade', 'É uma infração política grave cometida pelo presidente ou outros governantes que ataca a Constituição, as leis do orçamento ou o bom funcionamento do governo.', 'Infração de natureza político-administrativa típica, regulada pela Lei nº 1.079/1950 e prevista no art. 85 da CF/88. Passível de culminar na perda do cargo e inabilitação temporária.', 'institucional', 'A abertura de créditos orçamentários sem aval do Congresso configurou crime de responsabilidade.', ARRAY['impeachment','tcu','cgu']),

('tcu', 'Tribunal de Contas da União (TCU)', 'É o órgão técnico que ajuda o Congresso Nacional a vigiar como o governo federal gasta as verbas dos impostos para evitar desperdícios e roubos.', 'Órgão constitucional autônomo de controle externo que assessora o Congresso Nacional na fiscalização contábil, orçamentária e financeira da União e entidades federais, regulado pelo art. 71 da CF/88.', 'institucional', 'O TCU suspendeu cautelarmente o contrato de obras rodoviárias por indícios de superfaturamento.', ARRAY['cgu','portal-da-transparencia','siafi']),

('cgu', 'Controladoria-Geral da União (CGU)', 'É o órgão interno do próprio governo focado em auditar ministérios, combater a corrupção e garantir que portais e dados públicos estejam abertos à sociedade.', 'Órgão do Poder Executivo Federal incumbido das ações de controle interno, auditoria, ouvidoria, correição administrativa e fomento à integridade e à transparência pública, regulado pela Lei nº 13.844/2019.', 'institucional', 'A CGU realizou auditoria em convênios federais firmados com prefeituras para o saneamento.', ARRAY['tcu','portal-da-transparencia','prestacao-de-contas']),

('portal-da-transparencia', 'Portal da Transparência', 'É um site público onde qualquer pessoa pode ver gratuitamente o dinheiro que o governo arrecada e como ele é gasto de verdade no dia a dia.', 'Sítio eletrônico oficial gerido pela administração pública que disponibiliza dados estruturados de execução orçamentária, convênios, despesas e contratos públicos, nos termos da Lei nº 12.527/2011.', 'institucional', 'O cidadão acessou o Portal da Transparência para monitorar os gastos indenizatórios da prefeitura.', ARRAY['siafi','tcu','cgu']),

('siafi', 'SIAFI', 'É o sistema eletrônico e contábil gigante utilizado pelo governo federal para planejar, registrar e controlar tudo o que a União gasta ou recebe no dia a dia.', 'Sistema Integrado de Administração Financeira do Governo Federal, instituído pelo Decreto nº 347/1991. Funciona como software contábil oficial que registra a execução financeira federal.', 'financeiro', 'A emissão da Nota de Empenho orçamentária foi devidamente processada por meio do SIAFI.', ARRAY['portal-da-transparencia','cgu','tcu'])

ON CONFLICT (slug) DO UPDATE SET
  termo               = EXCLUDED.termo,
  definicao_simples   = EXCLUDED.definicao_simples,
  definicao_tecnica   = EXCLUDED.definicao_tecnica,
  categoria           = EXCLUDED.categoria,
  exemplo             = EXCLUDED.exemplo,
  termos_relacionados = EXCLUDED.termos_relacionados,
  atualizado_em       = now();

-- Verificação final
SELECT COUNT(*) as total, COUNT(DISTINCT slug) as slugs_unicos FROM glossario;
