-- ============================================================
-- Seed do Glossário Político — 40 termos iniciais
-- ============================================================

INSERT INTO glossario (slug, termo, definicao_simples, definicao_tecnica, categoria, exemplo, termos_relacionados) VALUES

-- LEGISLATIVO
('projeto-de-lei', 'Projeto de Lei',
 'Uma proposta formal para criar ou mudar uma lei no Brasil. Qualquer deputado, senador ou até o cidadão (com 1% das assinaturas dos eleitores) pode apresentar um PL.',
 'Instrumento legislativo previsto no art. 61 da Constituição Federal. Tramita pela Câmara dos Deputados e pelo Senado Federal antes de ir à sanção presidencial.',
 'legislativo',
 'O PL 1234/2024 propõe reduzir o IPI sobre bicicletas.',
 ARRAY['plenario', 'votacao-nominal', 'sancao-presidencial']),

('proposta-de-emenda-constitucional', 'PEC — Proposta de Emenda Constitucional',
 'Uma proposta para mudar a Constituição Federal — a lei mais importante do Brasil. É mais difícil de aprovar que um PL: precisa de 3/5 dos votos em duas votações em cada câmara.',
 'Instrumento previsto no art. 60 da CF/88. Requer aprovação em dois turnos, com maioria de 3/5 em cada turno, tanto na Câmara quanto no Senado. Não pode ser objeto de deliberação proposta de abolição de cláusulas pétreas.',
 'legislativo',
 'A PEC 45/2019 reformou o sistema tributário brasileiro.',
 ARRAY['clausula-petrea', 'votacao-nominal', 'quorum']),

('plenario', 'Plenário',
 'O salão principal do Congresso onde todos os deputados ou senadores se reúnem para votar as leis mais importantes.',
 'Órgão deliberativo máximo da Casa Legislativa, composto por todos os membros eleitos. As votações em plenário são as definitivas para aprovação de proposições.',
 'legislativo',
 'A votação da reforma tributária foi realizada no plenário da Câmara.',
 ARRAY['votacao-nominal', 'quorum', 'sessao-plenaria']),

('sessao-plenaria', 'Sessão Plenária',
 'A reunião oficial dos deputados ou senadores para discutir e votar propostas de lei. Pode ser ordinária (reuniões programadas) ou extraordinária (convocada para urgências).',
 'Reunião deliberativa da Casa Legislativa, regida por normas do Regimento Interno. As sessões ordinárias ocorrem em dias e horários definidos no calendário legislativo.',
 'legislativo',
 'Na sessão de terça-feira, os deputados aprovaram o orçamento da União.',
 ARRAY['plenario', 'quorum', 'votacao-nominal']),

('votacao-nominal', 'Votação Nominal',
 'Uma votação onde o voto de cada parlamentar fica registrado publicamente — você pode ver se seu deputado votou sim ou não.',
 'Modalidade de votação prevista no Regimento Interno, em que cada parlamentar registra seu voto individualmente por meio eletrônico ou chamada nominal, ficando o resultado disponível para consulta pública.',
 'legislativo',
 'Na votação nominal sobre a reforma da previdência, cada deputado teve seu voto publicado.',
 ARRAY['plenario', 'sessao-plenaria', 'ausencia']),

('quorum', 'Quórum',
 'O número mínimo de parlamentares que precisam estar presentes para que uma votação seja válida. Para leis comuns é maioria simples; para mudar a Constituição é 2/3.',
 'Número mínimo de membros presentes para que deliberações sejam válidas. O quórum de instalação é a maioria absoluta (metade mais um). Para diferentes proposições, exige-se maioria simples, absoluta, qualificada (3/5) ou especial (2/3).',
 'legislativo',
 'A sessão foi encerrada por falta de quórum — apenas 30 dos 81 senadores estavam presentes.',
 ARRAY['votacao-nominal', 'sessao-plenaria', 'ausencia']),

('comissao-parlamentar', 'Comissão Parlamentar',
 'Um grupo menor de parlamentares com especialidade em uma área (saúde, educação, economia) que analisa os projetos antes de irem ao plenário.',
 'Órgão colegiado interno da Casa Legislativa, previsto no art. 58 da CF/88. Pode ser permanente (ex: CCJ, CFT) ou temporária (ex: CPIs, comissões especiais). Emite pareceres e pode ter poder terminativo sobre projetos.',
 'legislativo',
 'A Comissão de Saúde aprovou o projeto antes de ir a votação no plenário.',
 ARRAY['comissao-parlamentar-de-inquerito', 'plenario', 'projeto-de-lei']),

('comissao-parlamentar-de-inquerito', 'CPI — Comissão Parlamentar de Inquérito',
 'Uma comissão especial criada para investigar irregularidades no governo ou em empresas. Tem poderes semelhantes aos de um juiz: pode convocar pessoas e pedir documentos sigilosos.',
 'Comissão temporária com poderes investigativos próprios das autoridades judiciais (art. 58, §3º, CF/88). Criada a partir de 1/3 dos membros da Casa, deve ter objeto determinado e prazo certo.',
 'legislativo',
 'A CPI da Pandemia investigou a compra de vacinas pelo governo federal em 2021.',
 ARRAY['comissao-parlamentar', 'prerrogativas-parlamentares']),

('obstrucao', 'Obstrução',
 'Quando um parlamentar se recusa a votar como forma de protesto ou estratégia política. O voto de obstrução é contado, mas não decide o resultado.',
 'Recurso regimental pelo qual o parlamentar registra presença mas recusa participar da votação, geralmente por discordância com o processo ou como estratégia de bancada. Não é computado como voto válido na maioria dos casos.',
 'legislativo',
 'A oposição usou a obstrução para protestar contra a votação em regime de urgência.',
 ARRAY['votacao-nominal', 'bancada']),

('bancada', 'Bancada',
 'O conjunto de parlamentares de um mesmo partido ou estado que votam juntos e têm posições políticas comuns.',
 'Agrupamento formal de parlamentares por partido (bancada partidária) ou por tema (frente parlamentar). As bancadas temáticas, como a bancada ruralista ou a bancada da saúde, reúnem parlamentares de diferentes partidos.',
 'legislativo',
 'A bancada do PT votou contra o projeto de privatização.',
 ARRAY['partido-politico', 'votacao-nominal']),

-- FINANCEIRO
('cota-parlamentar', 'Cota Parlamentar',
 'O valor que cada deputado recebe para pagar despesas do seu trabalho como parlamentar: passagens, combustível, hospedagem, materiais de escritório. Não é salário — só pode ser usado para fins específicos.',
 'Denominada CEAP (Cota para Exercício da Atividade Parlamentar). Valor mensal variável por UF (de ~R$30.000 a R$45.000), regulamentada pelo Ato da Mesa nº 43/2009. Uso indevido pode gerar ressarcimento e processo disciplinar.',
 'financeiro',
 'O deputado usou R$4.200 da cota parlamentar para passagens aéreas em março.',
 ARRAY['emenda-parlamentar', 'salario-parlamentar']),

('ceap', 'CEAP — Cota para Exercício da Atividade Parlamentar',
 'O nome oficial da verba que os deputados recebem para pagar custos do trabalho parlamentar, como passagens e hospedagem. Popularmente chamada de "cota parlamentar".',
 'Regulamentada pelo Ato da Mesa nº 43/2009. O valor máximo mensal varia conforme a UF do deputado. Todos os gastos são públicos e podem ser consultados no portal de dados abertos da Câmara.',
 'financeiro',
 'Os dados de CEAP são publicados mensalmente pela Câmara dos Deputados.',
 ARRAY['cota-parlamentar', 'transparencia']),

('emenda-parlamentar', 'Emenda Parlamentar',
 'Uma verba que cada parlamentar tem direito de direcionar para obras e serviços no seu estado ou município — hospitais, estradas, escolas. É uma das formas mais diretas de um deputado beneficiar sua região.',
 'Instrumento previsto na LDO e LOA pelo qual parlamentares indicam recursos do orçamento federal para programas e ações específicas. Existem emendas individuais, de bancada e de comissão. As emendas individuais têm execução obrigatória (impositivas) desde a EC 86/2015.',
 'financeiro',
 'O deputado destinou R$2 milhões em emendas para a construção de UBSs na sua cidade.',
 ARRAY['cota-parlamentar', 'orcamento-publico']),

('orcamento-publico', 'Orçamento Público',
 'O plano anual do governo com quanto vai arrecadar e em que vai gastar. O Congresso vota e aprova o orçamento, e os parlamentares podem incluir emendas para direcionar recursos.',
 'Peça orçamentária composta pelo PPA (4 anos), LDO e LOA (anuais). Aprovado pelo Congresso Nacional, o orçamento define os limites de gastos da União. A LOA (Lei Orçamentária Anual) deve ser aprovada até 31 de dezembro.',
 'financeiro',
 'O orçamento de 2025 prevê R$2,2 trilhões em gastos da União.',
 ARRAY['emenda-parlamentar', 'lei-orçamentaria-anual']),

('salario-parlamentar', 'Subsídio Parlamentar',
 'O salário que deputados e senadores recebem mensalmente pelo cargo. Em 2024, o valor era de R$46.364,57 por mês, mais benefícios como plano de saúde e auxílio-moradia.',
 'Denominado "subsídio" nos termos do art. 39, §4º da CF/88. Fixado pelo Congresso Nacional e limitado ao subsídio dos ministros do STF. Não pode ser objeto de emolumentos, gratificações, adicionais ou abono.',
 'financeiro',
 'O subsídio dos parlamentares é fixado por resolução do Congresso Nacional.',
 ARRAY['cota-parlamentar', 'emenda-parlamentar']),

-- ELEITORAL
('candidatura', 'Candidatura',
 'O registro oficial de uma pessoa que quer disputar um cargo público nas eleições. Para ser candidato, é preciso se filiar a um partido e ter o registro aprovado pela Justiça Eleitoral.',
 'Ato pelo qual o partido indica seus candidatos à Justiça Eleitoral, nos prazos e condições da Lei nº 9.504/1997 (Lei das Eleições). O TSE e os TREs analisam e deferem ou indeferem as candidaturas.',
 'eleitoral',
 'A candidatura de João Silva ao Senado foi deferida pelo TSE.',
 ARRAY['partido-politico', 'ficha-limpa', 'tse']),

('ficha-limpa', 'Ficha Limpa',
 'Uma lei que impede pessoas condenadas por órgãos colegiados de tribunais de se candidatarem. Aprovada em 2010 após uma campanha popular com mais de 1,3 milhão de assinaturas.',
 'Lei Complementar nº 135/2010, que alterou a Lei das Inelegibilidades (LC 64/1990). Torna inelegível por 8 anos o candidato condenado por órgão colegiado, independentemente de trânsito em julgado.',
 'eleitoral',
 'O político teve sua candidatura barrada pela Lei da Ficha Limpa após condenação no TRE.',
 ARRAY['candidatura', 'tse', 'inelegibilidade']),

('inelegibilidade', 'Inelegibilidade',
 'Quando uma pessoa está impedida de se candidatar a um cargo público. Isso pode acontecer por condenação na Justiça, por ser parente de quem já está no cargo, ou por irregularidades nas contas.',
 'Condição jurídica que impede o cidadão de concorrer a mandatos eletivos. Pode ser constitucional (art. 14, §§ 4º a 8º, CF/88) ou infraconstitucional (LC 64/1990, alterada pela LC 135/2010 — Ficha Limpa).',
 'eleitoral',
 'A inelegibilidade por parentesco impede que um prefeito coloque o cônjuge como candidato na mesma eleição.',
 ARRAY['ficha-limpa', 'candidatura', 'tse']),

('colegio-eleitoral', 'Colégio Eleitoral',
 'O conjunto de eleitores registrados no TSE que têm direito a votar. No Brasil, votar é obrigatório para maiores de 18 anos e facultativo para jovens de 16-17 anos e maiores de 70.',
 'Corpo de eleitores alistados no Brasil, composto por cidadãos entre 18 e 70 anos (obrigatório) e facultativo para analfabetos, maiores de 70 e entre 16-17 anos. O alistamento é regulado pela Lei nº 9.504/1997.',
 'eleitoral',
 'O colégio eleitoral brasileiro tem mais de 156 milhões de eleitores.',
 ARRAY['tse', 'candidatura']),

('tse', 'TSE — Tribunal Superior Eleitoral',
 'O tribunal mais alto responsável por organizar as eleições no Brasil, julgar recursos eleitorais e fiscalizar partidos políticos e candidatos.',
 'Órgão de cúpula da Justiça Eleitoral (art. 119, CF/88). Composto por 7 ministros (3 do STF, 2 do STJ, 2 advogados indicados pelo STF). Competência para registrar partidos, julgar recursos e fixar jurisprudência eleitoral.',
 'eleitoral',
 'O TSE é responsável pelo sistema eletrônico de votação usado em todas as eleições brasileiras.',
 ARRAY['candidatura', 'ficha-limpa', 'partido-politico']),

-- INSTITUCIONAL
('partido-politico', 'Partido Político',
 'Uma organização de pessoas com ideias parecidas que se unem para disputar eleições e exercer o poder político. No Brasil, é obrigatório ser filiado a um partido para ser candidato.',
 'Pessoa jurídica de direito privado regulada pela Lei nº 9.096/1995. Para ter registro definitivo no TSE, precisa de apoiamento mínimo de eleitores. Recebem recursos do Fundo Partidário e acesso ao HGPE (horário eleitoral gratuito).',
 'institucional',
 'O PT (Partido dos Trabalhadores) foi fundado em 1980 e elegeu Lula presidente em 2002, 2006 e 2022.',
 ARRAY['candidatura', 'bancada', 'fundo-eleitoral']),

('fundo-eleitoral', 'Fundo Eleitoral',
 'Uma verba pública — dinheiro do governo — distribuída aos partidos políticos para financiar campanhas eleitorais. Em 2022, o fundo tinha R$4,9 bilhões.',
 'Fundo Especial de Financiamento de Campanha (FEFC), criado pela Lei nº 13.487/2017 após o STF proibir o financiamento privado por empresas. Distribuído pelo TSE entre os partidos com base em critérios como representação na Câmara.',
 'financeiro',
 'O partido recebeu R$50 milhões do fundo eleitoral para a campanha de 2022.',
 ARRAY['partido-politico', 'tse', 'candidatura']),

('mandato', 'Mandato',
 'O período em que um político eleito pode exercer o cargo. Deputados federais têm mandato de 4 anos; senadores, de 8 anos; presidente e governadores, de 4 anos (com possibilidade de reeleição).',
 'Período de exercício do cargo eletivo. Deputados: 4 anos. Senadores: 8 anos (eleições alternadas, por blocos de 1/3 e 2/3). Presidente e Governadores: 4 anos, com uma reeleição permitida. Prefeitos: 4 anos, com uma reeleição.',
 'institucional',
 'O mandato do senador começa em fevereiro do ano seguinte à eleição.',
 ARRAY['candidatura', 'legislatura']),

('legislatura', 'Legislatura',
 'O período de 4 anos em que um grupo de parlamentares exerce seu mandato. A legislatura atual no Brasil é a 57ª, que vai de 2023 a 2027.',
 'Período de 4 anos de atividade do Poder Legislativo correspondente ao mandato dos deputados federais (art. 44, parágrafo único, CF/88). Cada legislatura é subdividida em 4 sessões legislativas ordinárias.',
 'institucional',
 'A 57ª legislatura da Câmara dos Deputados começou em fevereiro de 2023.',
 ARRAY['mandato', 'sessao-plenaria']),

('sancao-presidencial', 'Sanção Presidencial',
 'Quando o presidente assina um projeto aprovado pelo Congresso, transformando-o em lei. Se o presidente discordar, pode vetar — total ou parcialmente — mas o Congresso pode derrubar o veto.',
 'Ato do Presidente da República que converte projeto de lei aprovado pelo Congresso em lei. Prevista no art. 66 da CF/88. O prazo é de 15 dias úteis. O silêncio implica sanção tácita. O veto pode ser total ou parcial e é apreciado pelo Congresso.',
 'legislativo',
 'O presidente vetou parcialmente o projeto, sancionando 90% do texto e vetando os artigos que aumentavam os gastos.',
 ARRAY['projeto-de-lei', 'veto-presidencial']),

('veto-presidencial', 'Veto Presidencial',
 'Quando o presidente recusa assinar um projeto aprovado pelo Congresso porque considera inconstitucional ou contrário ao interesse público. O Congresso pode derrubar o veto com maioria absoluta.',
 'Faculdade prevista no art. 66, §1º da CF/88. Pode ser total (rejeição integral) ou parcial (supressão de artigos). O veto suspende a promulgação e é enviado ao Congresso, que pode mantê-lo ou derrubá-lo em sessão conjunta por maioria absoluta.',
 'legislativo',
 'O Congresso derrubou o veto presidencial sobre o salário mínimo com 300 votos favoráveis.',
 ARRAY['sancao-presidencial', 'projeto-de-lei']),

('clausula-petrea', 'Cláusula Pétrea',
 'Partes da Constituição que não podem ser mudadas nunca, nem por emenda constitucional. São protegidas para sempre: o voto direto, a separação dos poderes, os direitos fundamentais e a federação.',
 'Limitação material ao poder de reforma constitucional, prevista no art. 60, §4º da CF/88. São cláusulas pétreas: a forma federativa de Estado, o voto direto secreto universal e periódico, a separação dos Poderes e os direitos e garantias individuais.',
 'legislativo',
 'O direito ao voto secreto é uma cláusula pétrea — nenhuma PEC pode acabar com ele.',
 ARRAY['proposta-de-emenda-constitucional', 'constituicao-federal']),

('constituicao-federal', 'Constituição Federal',
 'A lei mais importante do Brasil, aprovada em 1988. Ela define os direitos e deveres de todos os cidadãos, como o governo deve funcionar, e não pode ser mudada facilmente.',
 'Lei Fundamental do Estado brasileiro, promulgada em 5 de outubro de 1988. Composta por 250 artigos e 98 emendas constitucionais (até 2024). Estabelece os fundamentos, objetivos, direitos fundamentais e organização do Estado.',
 'institucional',
 'A Constituição Federal de 1988 garantiu o direito à saúde, educação e moradia a todos os brasileiros.',
 ARRAY['clausula-petrea', 'proposta-de-emenda-constitucional', 'diretos-fundamentais']),

('requerimento-de-urgencia', 'Requerimento de Urgência',
 'Um pedido para acelerar a votação de um projeto — pulando etapas normais de análise. Se aprovado, o projeto pode ser votado no mesmo dia sem passar pelas comissões.',
 'Instrumento regimental que permite à Mesa ou à maioria dos membros da Casa solicitar a apreciação imediata de uma proposição, suprimindo ou abreviando a tramitação ordinária.',
 'legislativo',
 'O governo pediu urgência na votação do orçamento para aprová-lo antes do recesso.',
 ARRAY['projeto-de-lei', 'plenario', 'comissao-parlamentar']),

('sessao-legislativa', 'Sessão Legislativa',
 'O ano de trabalho do Congresso. Cada mandato (4 anos) tem 4 sessões legislativas. O Congresso trabalha de fevereiro a julho e de agosto a dezembro, com recessos em janeiro e julho.',
 'Período anual de atividades do Congresso Nacional (art. 57, CF/88). A sessão legislativa ordinária vai de 2 de fevereiro a 17 de julho e de 1º de agosto a 22 de dezembro. Existe também sessão legislativa extraordinária, convocada no recesso.',
 'legislativo',
 'A sessão legislativa de 2025 começa em 2 de fevereiro com o discurso do presidente do Senado.',
 ARRAY['legislatura', 'sessao-plenaria', 'recesso']),

('recesso', 'Recesso Parlamentar',
 'O período de férias do Congresso — janeiro e julho. Durante o recesso, o presidente pode convocar os parlamentares para sessões extraordinárias em casos urgentes.',
 'Períodos de suspensão dos trabalhos legislativos ordinários: janeiro (01/01 a 01/02) e julho (18/07 a 31/07). Durante o recesso, é possível convocar sessão legislativa extraordinária pelo Presidente da República, da Câmara ou do Senado.',
 'legislativo',
 'O projeto foi votado durante o recesso após convocação extraordinária pelo Presidente da República.',
 ARRAY['sessao-legislativa', 'sessao-plenaria']),

('presidencia-da-republica', 'Presidência da República',
 'O cargo mais alto do Poder Executivo federal — o presidente governa o Brasil por 4 anos e pode ser reeleito uma vez. É eleito por voto direto em dois turnos.',
 'Chefe do Poder Executivo Federal (art. 76 e ss. da CF/88). Mandato de 4 anos com uma reeleição consecutiva permitida. Eleito pelo sistema de maioria absoluta (dois turnos se necessário). Pode sofrer impeachment por crime de responsabilidade.',
 'institucional',
 'O presidente assinou o decreto que regulamentou a reforma tributária aprovada pelo Congresso.',
 ARRAY['sancao-presidencial', 'veto-presidencial', 'impeachment']),

('impeachment', 'Impeachment',
 'O processo de destituição de um presidente, governador ou prefeito por crime de responsabilidade. No Brasil, é julgado pelo Senado e precisa de 2/3 dos votos para tirar o mandato.',
 'Processo de responsabilização político-jurídica do Presidente da República (art. 86, CF/88) por crime de responsabilidade (Lei nº 1.079/1950). A Câmara autoriza (2/3 de votos) e o Senado julga e condena (2/3 de votos), com presidência do STF.',
 'institucional',
 'O Brasil teve dois impeachments presidenciais: Collor (1992) e Dilma (2016).',
 ARRAY['presidencia-da-republica', 'crime-de-responsabilidade']),

('transparencia', 'Transparência Pública',
 'A obrigação dos governos de divulgar informações sobre o que fazem e como gastam o dinheiro público. No Brasil, a Lei de Acesso à Informação garante ao cidadão o direito de pedir qualquer dado governamental.',
 'Princípio constitucional (art. 37, CF/88) e obrigação legal (Lei nº 12.527/2011 — LAI). Inclui a publicidade ativa (divulgação espontânea) e passiva (resposta a pedidos de acesso). O Portal da Transparência da CGU é o principal canal federal.',
 'institucional',
 'Pela Lei de Acesso à Informação, qualquer cidadão pode pedir ao governo informações sobre contratos públicos.',
 ARRAY['cota-parlamentar', 'emenda-parlamentar', 'orcamento-publico']),

('prerrogativas-parlamentares', 'Imunidade Parlamentar',
 'A proteção legal que deputados e senadores têm para exercer seu mandato com liberdade: não podem ser presos (exceto em flagrante de crime grave) e não respondem judicialmente pelo que dizem no exercício do mandato.',
 'Garantia constitucional (art. 53, CF/88) que assegura inviolabilidade civil e penal por opiniões, palavras e votos no exercício do mandato (imunidade material). A imunidade processual impede prisão salvo flagrante de crime inafiançável.',
 'institucional',
 'O deputado usou a imunidade parlamentar para fazer declarações em plenário sem risco de processo civil.',
 ARRAY['comissao-parlamentar-de-inquerito', 'plenario']),

('medida-provisoria', 'Medida Provisória',
 'Uma lei temporária que o presidente pode criar sozinho em casos de urgência, sem precisar do Congresso. Tem força de lei imediata, mas expira em 60 dias se o Congresso não a aprovar.',
 'Instrumento previsto no art. 62 da CF/88, editado pelo Presidente da República em caso de relevância e urgência. Vige por 60 dias, prorrogáveis por igual período. Se não convertida em lei, perde a eficácia ex tunc (como se nunca tivesse existido).',
 'institucional',
 'O presidente editou uma MP para aumentar o salário mínimo antes que o Congresso aprovasse a lei.',
 ARRAY['projeto-de-lei', 'sancao-presidencial', 'presidencia-da-republica']),

('cpf-na-nota', 'CPF na Nota / Nota Fiscal',
 'O pedido para incluir seu CPF na nota fiscal de compras. O dinheiro dos impostos pagos na compra fica registrado no seu nome, e alguns estados oferecem descontos no IPVA ou sorteios como incentivo.',
 'Mecanismo de cidadania fiscal que incentiva a emissão de notas fiscais eletrônicas ao vincular o CPF do consumidor. Cada estado tem sua legislação própria. Além dos benefícios individuais, aumenta a arrecadação ao combater a sonegação.',
 'financeiro',
 'Ao informar o CPF na nota em SP, o consumidor acumula créditos no programa Nota Fiscal Paulista.',
 ARRAY['transparencia', 'orcamento-publico']),

('coligacao', 'Coligação / Federação Partidária',
 'A união formal de dois ou mais partidos para disputar uma eleição juntos. Hoje, no Brasil, os partidos formam federações que duram pelo menos 4 anos — mais permanentes que as antigas coligações.',
 'A EC 97/2017 extinguiu coligações proporcionais. Substituídas pelas federações partidárias (Res. TSE nº 23.670/2021), que exigem fidelidade por no mínimo 4 anos. Federações atuam como partido único para fins eleitorais e de fundo eleitoral.',
 'eleitoral',
 'PT, PV e PCdoB formaram uma federação para as eleições de 2022.',
 ARRAY['partido-politico', 'fundo-eleitoral', 'candidatura']),

('suplente', 'Suplente',
 'O "substituto" de um senador ou deputado — quando o titular assume outro cargo ou fica impossibilitado de exercer o mandato, o suplente ocupa o lugar temporariamente.',
 'Figura jurídica do direito eleitoral que garante a continuidade do mandato em caso de vacância ou licença do titular. Senadores têm 2 suplentes eleitos junto. Deputados: o suplente é o próximo na lista partidária.',
 'eleitoral',
 'Quando o senador assumiu a vaga de ministro, o primeiro suplente tomou posse.',
 ARRAY['mandato', 'candidatura', 'partido-politico']),

('sessao-conjunta', 'Sessão Conjunta do Congresso',
 'Uma reunião de todos os deputados e senadores juntos no mesmo plenário. Acontece para inaugurar o ano legislativo, apreciar vetos presidenciais e aprovar o orçamento.',
 'Reunião simultânea da Câmara dos Deputados e do Senado Federal, presidida pelo Presidente do Senado. Prevista nos arts. 57, §3º e 66, §4º da CF/88 para fins específicos: inauguração da sessão legislativa, deliberação sobre vetos, orçamento e EC aprovada em segundo turno.',
 'legislativo',
 'O Congresso reuniu-se em sessão conjunta para votar o orçamento de 2025.',
 ARRAY['sessao-plenaria', 'legislatura', 'orcamento-publico']);
